name = "CarboKitten"
uuid = "690c6d5c-626a-429f-a06b-981a1dae1c19"
authors = ["Johan Hidding <j.hidding@esciencecenter.nl>"]
version = "0.2.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ModuleMixins = "2b5f0a26-aae2-5c4c-af55-bc6d20297121"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[weakdeps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extensions]
VisualizationExt = ["Makie", "Statistics", "GeometryBasics"]

[compat]
AxisArrays = "0.4"
HDF5 = "0.17"
TerminalLoggers = "0.1.7"
Transducers = "0.4"
Unitful = "1"
julia = "1.10"
