[deps]
CarboKitten = "690c6d5c-626a-429f-a06b-981a1dae1c19"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterMermaid = "a078cd44-4d9c-4618-b545-3ab9d77f9177"
GraphvizDotLang = "6039e64d-d8b8-4c93-8e43-7efd2f757352"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MarkdownAST = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"
ModuleMixins = "2b5f0a26-aae2-5c4c-af55-bc6d20297121"
Smoothers = "012d725f-b4dd-4916-8440-03955fc52575"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[sources]
CarboKitten = {path = ".."}
ModuleMixins = {rev = "main", url = "https://github.com/jhidding/ModuleMixins.jl"}
