[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CarboKitten = "690c6d5c-626a-429f-a06b-981a1dae1c19"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DaemonMode = "d749ddd5-2b29-4920-8305-6ff5a704e36e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GraphvizDotLang = "6039e64d-d8b8-4c93-8e43-7efd2f757352"
Graphviz_jll = "3c863552-8265-54e4-a6dc-903eb78fde85"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModuleMixins = "2b5f0a26-aae2-5c4c-af55-bc6d20297121"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProfileCanvas = "efd6af41-a80b-495e-886c-e51b0c7d77a3"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Smoothers = "012d725f-b4dd-4916-8440-03955fc52575"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"
